export const topologyData = [
  {
    nmap: {
      command_line:
        "nmap -oX - -sS -sV --version-intensity 5 -O --osscan-guess --fuzzy --max-os-tries 8 --max-retries 4 -PE -Pn -PP --top-port 15 --min-hostgroup 64 192.168.100.1",
      scaninfo: {
        tcp: {
          method: "syn",
          services: "21-23,25,53,80,110,135,139,143,443,445,3306,3389,8080",
        },
      },
      scanstats: {
        timestr: "Thu Jun 20 19:28:16 2024",
        elapsed: "20.59",
        uphosts: "1",
        downhosts: "0",
        totalhosts: "1",
      },
    },
    scan: {
      "192.168.100.1": {
        hostnames: [
          {
            name: "",
            type: "",
          },
        ],
        addresses: {
          ipv4: "192.168.100.1",
          mac: "48:D5:39:E8:B2:5A",
        },
        vendor: {
          "48:D5:39:E8:B2:5A": "Huawei Technologies",
        },
        status: {
          state: "up",
          reason: "arp-response",
        },
        uptime: {
          seconds: "99360",
          lastboot: "Wed Jun 19 15:52:16 2024",
        },
        tcp: {
          21: {
            state: "filtered",
            reason: "no-response",
            name: "ftp",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          22: {
            state: "filtered",
            reason: "no-response",
            name: "ssh",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          23: {
            state: "open",
            reason: "syn-ack",
            name: "telnet",
            product: "Huawei Home Gateway telnetd",
            version: "",
            extrainfo: "",
            conf: "10",
            cpe: "",
          },
          25: {
            state: "closed",
            reason: "reset",
            name: "smtp",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          53: {
            state: "open",
            reason: "syn-ack",
            name: "domain",
            product: "",
            version: "",
            extrainfo: "unknown banner: Nein",
            conf: "10",
            cpe: "",
          },
          80: {
            state: "open",
            reason: "syn-ack",
            name: "http",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          110: {
            state: "closed",
            reason: "reset",
            name: "pop3",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          135: {
            state: "closed",
            reason: "reset",
            name: "msrpc",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          139: {
            state: "closed",
            reason: "reset",
            name: "netbios-ssn",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          143: {
            state: "closed",
            reason: "reset",
            name: "imap",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          443: {
            state: "closed",
            reason: "reset",
            name: "https",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          445: {
            state: "closed",
            reason: "reset",
            name: "microsoft-ds",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          3306: {
            state: "closed",
            reason: "reset",
            name: "mysql",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          3389: {
            state: "closed",
            reason: "reset",
            name: "ms-wbt-server",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          8080: {
            state: "closed",
            reason: "reset",
            name: "http-proxy",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
        },
        portused: [
          {
            state: "open",
            proto: "tcp",
            portid: "23",
          },
          {
            state: "closed",
            proto: "tcp",
            portid: "25",
          },
          {
            state: "closed",
            proto: "udp",
            portid: "38150",
          },
        ],
        osmatch: [
          {
            name: "Linux 3.5",
            accuracy: "100",
            line: "65710",
            osclass: [
              {
                type: "general purpose",
                vendor: "Linux",
                osfamily: "Linux",
                osgen: "3.X",
                accuracy: "100",
                cpe: ["cpe:/o:linux:linux_kernel:3.5"],
              },
            ],
          },
        ],
      },
    },
    severity: "L",
  },
  {
    nmap: {
      command_line:
        "nmap -oX - -sS -sV --version-intensity 5 -O --osscan-guess --fuzzy --max-os-tries 8 --max-retries 4 -PE -Pn -PP --top-port 15 --min-hostgroup 64 192.168.100.10",
      scaninfo: {
        tcp: {
          method: "syn",
          services: "21-23,25,53,80,110,135,139,143,443,445,3306,3389,8080",
        },
      },
      scanstats: {
        timestr: "Thu Jun 20 19:28:25 2024",
        elapsed: "8.08",
        uphosts: "1",
        downhosts: "0",
        totalhosts: "1",
      },
    },
    scan: {
      "192.168.100.10": {
        hostnames: [
          {
            name: "host.docker.internal",
            type: "PTR",
          },
        ],
        addresses: {
          ipv4: "192.168.100.10",
        },
        vendor: {},
        status: {
          state: "up",
          reason: "user-set",
        },
        uptime: {
          seconds: "1027589",
          lastboot: "Sat Jun  8 22:01:56 2024",
        },
        tcp: {
          21: {
            state: "closed",
            reason: "reset",
            name: "ftp",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          22: {
            state: "closed",
            reason: "reset",
            name: "ssh",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          23: {
            state: "closed",
            reason: "reset",
            name: "telnet",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          25: {
            state: "closed",
            reason: "reset",
            name: "smtp",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          53: {
            state: "closed",
            reason: "reset",
            name: "domain",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          80: {
            state: "closed",
            reason: "reset",
            name: "http",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          110: {
            state: "closed",
            reason: "reset",
            name: "pop3",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          135: {
            state: "open",
            reason: "syn-ack",
            name: "msrpc",
            product: "Microsoft Windows RPC",
            version: "",
            extrainfo: "",
            conf: "10",
            cpe: "cpe:/o:microsoft:windows",
          },
          139: {
            state: "open",
            reason: "syn-ack",
            name: "netbios-ssn",
            product: "Microsoft Windows netbios-ssn",
            version: "",
            extrainfo: "",
            conf: "10",
            cpe: "cpe:/o:microsoft:windows",
          },
          143: {
            state: "closed",
            reason: "reset",
            name: "imap",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          443: {
            state: "closed",
            reason: "reset",
            name: "https",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          445: {
            state: "open",
            reason: "syn-ack",
            name: "microsoft-ds",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          3306: {
            state: "closed",
            reason: "reset",
            name: "mysql",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          3389: {
            state: "closed",
            reason: "reset",
            name: "ms-wbt-server",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
          8080: {
            state: "closed",
            reason: "reset",
            name: "http-proxy",
            product: "",
            version: "",
            extrainfo: "",
            conf: "3",
            cpe: "",
          },
        },
        portused: [
          {
            state: "open",
            proto: "tcp",
            portid: "135",
          },
          {
            state: "closed",
            proto: "tcp",
            portid: "21",
          },
          {
            state: "closed",
            proto: "udp",
            portid: "32268",
          },
        ],
        osmatch: [
          {
            name: "Microsoft Windows 10 1607",
            accuracy: "100",
            line: "69748",
            osclass: [
              {
                type: "general purpose",
                vendor: "Microsoft",
                osfamily: "Windows",
                osgen: "10",
                accuracy: "100",
                cpe: ["cpe:/o:microsoft:windows_10:1607"],
              },
            ],
          },
        ],
      },
    },
    severity: "L",
  },
];

// globe
const colors = ["#06b6d4", "#3b82f6", "#6366f1"];
export const sampleArcs = [
  {
    order: 1,
    startLat: -19.885592,
    startLng: -43.951191,
    endLat: -22.9068,
    endLng: -43.1729,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 1,
    startLat: 28.6139,
    startLng: 77.209,
    endLat: 3.139,
    endLng: 101.6869,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 1,
    startLat: -19.885592,
    startLng: -43.951191,
    endLat: -1.303396,
    endLng: 36.852443,
    arcAlt: 0.5,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 2,
    startLat: 1.3521,
    startLng: 103.8198,
    endLat: 35.6762,
    endLng: 139.6503,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 2,
    startLat: 51.5072,
    startLng: -0.1276,
    endLat: 3.139,
    endLng: 101.6869,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 2,
    startLat: -15.785493,
    startLng: -47.909029,
    endLat: 36.162809,
    endLng: -115.119411,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 3,
    startLat: -33.8688,
    startLng: 151.2093,
    endLat: 22.3193,
    endLng: 114.1694,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 3,
    startLat: 21.3099,
    startLng: -157.8581,
    endLat: 40.7128,
    endLng: -74.006,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 3,
    startLat: -6.2088,
    startLng: 106.8456,
    endLat: 51.5072,
    endLng: -0.1276,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 4,
    startLat: 11.986597,
    startLng: 8.571831,
    endLat: -15.595412,
    endLng: -56.05918,
    arcAlt: 0.5,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 4,
    startLat: -34.6037,
    startLng: -58.3816,
    endLat: 22.3193,
    endLng: 114.1694,
    arcAlt: 0.7,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 4,
    startLat: 51.5072,
    startLng: -0.1276,
    endLat: 48.8566,
    endLng: -2.3522,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 5,
    startLat: 14.5995,
    startLng: 120.9842,
    endLat: 51.5072,
    endLng: -0.1276,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 5,
    startLat: 1.3521,
    startLng: 103.8198,
    endLat: -33.8688,
    endLng: 151.2093,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 5,
    startLat: 34.0522,
    startLng: -118.2437,
    endLat: 48.8566,
    endLng: -2.3522,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 6,
    startLat: -15.432563,
    startLng: 28.315853,
    endLat: 1.094136,
    endLng: -63.34546,
    arcAlt: 0.7,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 6,
    startLat: 37.5665,
    startLng: 126.978,
    endLat: 35.6762,
    endLng: 139.6503,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 6,
    startLat: 22.3193,
    startLng: 114.1694,
    endLat: 51.5072,
    endLng: -0.1276,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 7,
    startLat: -19.885592,
    startLng: -43.951191,
    endLat: -15.595412,
    endLng: -56.05918,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 7,
    startLat: 48.8566,
    startLng: -2.3522,
    endLat: 52.52,
    endLng: 13.405,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 7,
    startLat: 52.52,
    startLng: 13.405,
    endLat: 34.0522,
    endLng: -118.2437,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 8,
    startLat: -8.833221,
    startLng: 13.264837,
    endLat: -33.936138,
    endLng: 18.436529,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 8,
    startLat: 49.2827,
    startLng: -123.1207,
    endLat: 52.3676,
    endLng: 4.9041,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 8,
    startLat: 1.3521,
    startLng: 103.8198,
    endLat: 40.7128,
    endLng: -74.006,
    arcAlt: 0.5,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 9,
    startLat: 51.5072,
    startLng: -0.1276,
    endLat: 34.0522,
    endLng: -118.2437,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 9,
    startLat: 22.3193,
    startLng: 114.1694,
    endLat: -22.9068,
    endLng: -43.1729,
    arcAlt: 0.7,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 9,
    startLat: 1.3521,
    startLng: 103.8198,
    endLat: -34.6037,
    endLng: -58.3816,
    arcAlt: 0.5,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 10,
    startLat: -22.9068,
    startLng: -43.1729,
    endLat: 28.6139,
    endLng: 77.209,
    arcAlt: 0.7,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 10,
    startLat: 34.0522,
    startLng: -118.2437,
    endLat: 31.2304,
    endLng: 121.4737,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 10,
    startLat: -6.2088,
    startLng: 106.8456,
    endLat: 52.3676,
    endLng: 4.9041,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 11,
    startLat: 41.9028,
    startLng: 12.4964,
    endLat: 34.0522,
    endLng: -118.2437,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 11,
    startLat: -6.2088,
    startLng: 106.8456,
    endLat: 31.2304,
    endLng: 121.4737,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 11,
    startLat: 22.3193,
    startLng: 114.1694,
    endLat: 1.3521,
    endLng: 103.8198,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 12,
    startLat: 34.0522,
    startLng: -118.2437,
    endLat: 37.7749,
    endLng: -122.4194,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 12,
    startLat: 35.6762,
    startLng: 139.6503,
    endLat: 22.3193,
    endLng: 114.1694,
    arcAlt: 0.2,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 12,
    startLat: 22.3193,
    startLng: 114.1694,
    endLat: 34.0522,
    endLng: -118.2437,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 13,
    startLat: 52.52,
    startLng: 13.405,
    endLat: 22.3193,
    endLng: 114.1694,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 13,
    startLat: 11.986597,
    startLng: 8.571831,
    endLat: 35.6762,
    endLng: 139.6503,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 13,
    startLat: -22.9068,
    startLng: -43.1729,
    endLat: -34.6037,
    endLng: -58.3816,
    arcAlt: 0.1,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
  {
    order: 14,
    startLat: -33.936138,
    startLng: 18.436529,
    endLat: 21.395643,
    endLng: 39.883798,
    arcAlt: 0.3,
    color: colors[Math.floor(Math.random() * (colors.length - 1))],
  },
];
